# Generated by Django 6.0.3 on 2026-03-27 22:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_listingcategories_listings_listingcomments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='status',
            field=models.CharField(choices=[('T', 'Active'), ('F', 'Inactive')], default='T', max_length=1),
        ),
        migrations.AlterField(
            model_name='listings',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='listings',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_listings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='WhatchList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_watchlist', to='auctions.listings')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
